### ISSUE TITLE
Kerl Integration

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iota.lib.py#61]
With the latest snapshot, IOTA switched to a new hashing algorithm, named Kerl:

- https://blog.iota.org/upgrades-updates-d12145e381eb
- https://github.com/iotaledger/kerl/

Integrate this new hashing algorithm into PyOTA:

| Functionality |Curl-P-27 | Curl-P-81     | Kerl   |
|:--|:--:|:--:|:--:|
|Address generation |   |      | V^ |
|Signature generation|   |     | V |
|Signature verification|   |   | V |
|Essence calculation (bundleHash)| | | V |
|Proof of Work         |   | V |   |
|Transaction Hash      |   | V |   |
|Milestone verification| V |   |   |

_Curl-P-N: N number of rounds_

_^ CheckSums are calculated using the **last** 9 trytes._ 

## todo

* [x] Address generation
    * [x] Implementation
    * [x] Rewrite unit tests
* [x] Signature generation
    * [x] Implementation
    * [x] Rewrite unit tests
* [x] Signature verification (new)
    * [x] Implementation
    * [x] Rewrite unit tests
* [x] Bundle hash
    * [x] Implementation
    * [x] Rewrite unit tests
* _N/A_ Proof of work
* [x] Transaction hash
    * [x] Implementation
    * [x] Rewrite unit tests
* _N/A_ Milestone verification

Additional issues:
* [x] Incorrect private keys when seed is longer than 81 trytes
* [x] Multisig integration
* [x] Refactor unit tests for private key digests
* [x] Remove legacy bundle validation
* [x] Replace Curl-P-27 with Curl-P-81

**Comment by todofixthis** [comment]
Known issue:  PyOTA does not generate keys correctly when seed is longer that 81 trytes.

**Comment by todofixthis** [comment]
IOTA changed another aspect of the hashing algo in the latest snapshot.  Fortunately, this one's easier to implement than the previous one (it's just a change to the number of rounds that Curl performs).  Issue description has been updated to reflect this.

**Comment by todofixthis** [comment]
Upgraded to Curl-P-81, and transaction hash unit tests have been updated.

Note:  [PyOTA-CCurl](/todofixthis/pyota-ccurl) will also need to be updated, and a new release prepared (probably will wait to do this until after `feature/kerl` is merged into `develop`).

**Comment by todofixthis** [comment]
Scheduled for release: 2.0.0
